apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-ikarskya
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-ikarskya:b301cb835857eefe602a81b7b3cd8c8b9e8b9183@sha256:8d0834a34c5f9ac3dea65f921973f245c58f9284790e212a23179331c6c9b39f
          name: container-image
